# These are supported funding model platforms

github: [olaflaitinen]
patreon: olaflaitinen
open_collective: olaflaitinen
ko_fi: olaflaitinen
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: olaflaitinen
issuehunt: olaflaitinen
otechie: olaflaitinen
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
